spring.application.name=tailor-app

# MySQL (Docker service name mysql-db)
spring.datasource.url=jdbc:mysql://mysql-db:3306/tailor_shop
spring.datasource.username=root
spring.datasource.password=root123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Thymeleaf
spring.thymeleaf.cache=false

server.port=8080
